adds on parts for Markku design Robocar for 1/10 HG-P402.
markku-ai/things pull request #1
Opened 2019-05-05 12:38 UTC by macfly1202

2019-05-08 18:47 UTC, majori requested changes
Thanks for contributing! Could you also include pictures/tutorial to README about how to assembly and how the final setup looks like?

2019-05-10 06:15 UTC, majori commented
Also could you move everything else but rail adapter to the `modules` directory, since there we have all the accessories for the rail.

2019-05-10 06:20 UTC, macfly1202 commented
Ok will do in the next hour.

Envoyé de mon iPhone

> Le 10 mai 2019 à 08:15, Antti Kivimäki <notifications@github.com> a écrit :
> 
> Also could you move everything else but rail adapter to the modules directory, since there we have all the accessories for the rail.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-14 11:51 UTC, majori approved these changes

2019-05-14 11:52 UTC, merged